[2023-04-10T01:00:07.619+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.store_user scheduled__2023-04-09T00:00:00+00:00 [queued]>
[2023-04-10T01:00:07.626+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.store_user scheduled__2023-04-09T00:00:00+00:00 [queued]>
[2023-04-10T01:00:07.627+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T01:00:07.628+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-10T01:00:07.629+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T01:00:07.637+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-04-09 00:00:00+00:00
[2023-04-10T01:00:07.644+0000] {standard_task_runner.py:55} INFO - Started process 16446 to run task
[2023-04-10T01:00:07.649+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'store_user', 'scheduled__2023-04-09T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpy9wx57j7']
[2023-04-10T01:00:07.652+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask store_user
[2023-04-10T01:00:07.782+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.store_user scheduled__2023-04-09T00:00:00+00:00 [running]> on host c12a518d534c
[2023-04-10T01:00:07.922+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-09T00:00:00+00:00
[2023-04-10T01:00:07.926+0000] {postgres.py:129} INFO - Running copy expert: COPY user_details FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-04-10T01:00:07.955+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-10T01:00:07.965+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-10T01:00:07.977+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=api_dag, task_id=store_user, execution_date=20230409T000000, start_date=20230410T010007, end_date=20230410T010007
[2023-04-10T01:00:08.026+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-10T01:00:08.043+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-11T17:26:52.043+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.store_user scheduled__2023-04-09T00:00:00+00:00 [queued]>
[2023-04-11T17:26:52.061+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.store_user scheduled__2023-04-09T00:00:00+00:00 [queued]>
[2023-04-11T17:26:52.063+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:26:52.064+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-11T17:26:52.065+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:26:52.077+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-04-09 00:00:00+00:00
[2023-04-11T17:26:52.094+0000] {standard_task_runner.py:55} INFO - Started process 39716 to run task
[2023-04-11T17:26:52.104+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'store_user', 'scheduled__2023-04-09T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmp8__nl3n6']
[2023-04-11T17:26:52.108+0000] {standard_task_runner.py:83} INFO - Job 125: Subtask store_user
[2023-04-11T17:26:52.257+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.store_user scheduled__2023-04-09T00:00:00+00:00 [running]> on host c12a518d534c
[2023-04-11T17:26:52.367+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-09T00:00:00+00:00
[2023-04-11T17:26:52.382+0000] {postgres.py:129} INFO - Running copy expert: COPY user_details FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-04-11T17:26:52.418+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-11T17:26:52.431+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api.py", line 15, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "user_details_username_key"
DETAIL:  Key (username)=(organicpeacock421) already exists.
CONTEXT:  COPY user_details, line 1

[2023-04-11T17:26:52.493+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=api_dag, task_id=store_user, execution_date=20230409T000000, start_date=20230411T172652, end_date=20230411T172652
[2023-04-11T17:26:52.528+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 125 for task store_user (duplicate key value violates unique constraint "user_details_username_key"
DETAIL:  Key (username)=(organicpeacock421) already exists.
CONTEXT:  COPY user_details, line 1
; 39716)
[2023-04-11T17:26:52.562+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-11T17:26:52.586+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
