[2023-04-11T20:39:39.085+0000] {processor.py:154} INFO - Started process (PID=8058) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:39:39.087+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:39:39.088+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:39:39.088+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:39:39.108+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:39:39.106+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:39:39.109+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:39:39.131+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.049 seconds
[2023-04-11T20:40:09.269+0000] {processor.py:154} INFO - Started process (PID=8125) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:40:09.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:40:09.297+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:40:09.297+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:40:09.311+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:40:09.309+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:40:09.315+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:40:09.338+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-11T20:40:39.563+0000] {processor.py:154} INFO - Started process (PID=8192) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:40:39.566+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:40:39.568+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:40:39.567+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:40:39.589+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:40:39.587+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:40:39.591+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:40:39.613+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.055 seconds
[2023-04-11T20:41:09.954+0000] {processor.py:154} INFO - Started process (PID=8259) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:41:09.958+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:41:09.959+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:41:09.959+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:41:09.971+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:41:09.968+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:41:09.973+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:41:09.992+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.042 seconds
[2023-04-11T20:41:40.914+0000] {processor.py:154} INFO - Started process (PID=8317) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:41:40.923+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:41:40.927+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:41:40.927+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:41:40.989+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:41:40.985+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:41:40.993+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:41:41.107+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.238 seconds
[2023-04-11T20:52:16.021+0000] {processor.py:154} INFO - Started process (PID=8375) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:52:16.023+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:52:16.025+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:52:16.025+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:52:16.069+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:52:16.057+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:52:16.071+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:52:16.135+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.119 seconds
[2023-04-11T20:52:46.348+0000] {processor.py:154} INFO - Started process (PID=8442) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:52:46.352+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:52:46.354+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:52:46.354+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:52:46.374+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:52:46.372+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:52:46.375+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:52:46.399+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.058 seconds
[2023-04-11T20:53:17.077+0000] {processor.py:154} INFO - Started process (PID=8500) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:53:17.079+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:53:17.083+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:53:17.083+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:53:17.101+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:53:17.097+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:53:17.103+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:53:17.125+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.053 seconds
[2023-04-11T20:53:47.518+0000] {processor.py:154} INFO - Started process (PID=8568) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:53:47.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:53:47.527+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:53:47.527+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:53:47.553+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:53:47.548+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:53:47.554+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:53:47.598+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.085 seconds
[2023-04-11T20:54:17.901+0000] {processor.py:154} INFO - Started process (PID=8635) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:54:17.908+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:54:17.912+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:54:17.912+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:54:17.960+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:54:17.929+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:54:17.962+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:54:17.995+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.099 seconds
[2023-04-11T20:54:48.225+0000] {processor.py:154} INFO - Started process (PID=8701) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:54:48.229+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:54:48.231+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:54:48.231+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:54:48.249+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:54:48.246+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:54:48.250+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:54:48.275+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.054 seconds
[2023-04-11T20:55:18.845+0000] {processor.py:154} INFO - Started process (PID=8769) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:55:18.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:55:18.850+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:55:18.850+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:55:18.879+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:55:18.876+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:55:18.880+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:55:18.908+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-11T20:55:49.367+0000] {processor.py:154} INFO - Started process (PID=8834) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:55:49.377+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:55:49.379+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:55:49.379+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:55:49.395+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:55:49.392+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:55:49.402+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:55:49.436+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-11T20:56:19.573+0000] {processor.py:154} INFO - Started process (PID=8894) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:56:19.576+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:56:19.577+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:56:19.577+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:56:19.599+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:56:19.597+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:56:19.601+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:56:19.623+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.056 seconds
[2023-04-11T20:56:49.929+0000] {processor.py:154} INFO - Started process (PID=8962) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:56:49.933+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:56:49.934+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:56:49.934+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:56:49.951+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:56:49.948+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:56:49.952+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:56:49.975+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.050 seconds
[2023-04-11T20:57:41.004+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:57:41.012+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:57:41.015+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:57:41.015+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:57:41.067+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:57:41.058+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:57:41.069+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:57:41.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.097 seconds
[2023-04-11T20:58:11.672+0000] {processor.py:154} INFO - Started process (PID=64) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:58:11.675+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:58:11.677+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:58:11.677+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:58:11.715+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:58:11.711+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:58:11.716+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:58:11.759+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.092 seconds
[2023-04-11T20:58:41.979+0000] {processor.py:154} INFO - Started process (PID=94) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:58:41.982+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:58:41.983+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:58:41.983+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:58:42.008+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:58:42.003+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:58:42.009+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:58:42.044+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-11T20:59:12.425+0000] {processor.py:154} INFO - Started process (PID=125) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:59:12.428+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:59:12.430+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:59:12.430+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:59:12.445+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:59:12.442+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:59:12.447+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:59:12.483+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.062 seconds
[2023-04-11T20:59:42.942+0000] {processor.py:154} INFO - Started process (PID=147) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T20:59:42.946+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T20:59:42.948+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:59:42.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T20:59:42.965+0000] {logging_mixin.py:120} INFO - [2023-04-11T20:59:42.962+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T20:59:42.967+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T20:59:42.993+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.056 seconds
[2023-04-11T21:00:13.261+0000] {processor.py:154} INFO - Started process (PID=177) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:00:13.263+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:00:13.266+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:00:13.266+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:00:13.290+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:00:13.286+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:00:13.292+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:00:13.322+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-11T21:00:43.421+0000] {processor.py:154} INFO - Started process (PID=209) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:00:43.426+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:00:43.429+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:00:43.429+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:00:43.475+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:00:43.448+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:00:43.477+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:00:43.500+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-11T21:01:13.796+0000] {processor.py:154} INFO - Started process (PID=222) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:01:13.799+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:01:13.800+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:01:13.800+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:01:13.837+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:01:13.835+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:01:13.839+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:01:13.862+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-11T21:01:43.927+0000] {processor.py:154} INFO - Started process (PID=254) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:01:43.936+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:01:43.938+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:01:43.938+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:01:43.954+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:01:43.952+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:01:43.962+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:01:43.986+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.065 seconds
[2023-04-11T21:02:14.056+0000] {processor.py:154} INFO - Started process (PID=285) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:02:14.059+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:02:14.060+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:02:14.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:02:14.081+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:02:14.078+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:02:14.082+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:02:14.103+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.051 seconds
[2023-04-11T21:02:44.286+0000] {processor.py:154} INFO - Started process (PID=315) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:02:44.289+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:02:44.314+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:02:44.313+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:02:44.337+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:02:44.332+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:02:44.339+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:02:44.373+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.097 seconds
[2023-04-11T21:03:14.810+0000] {processor.py:154} INFO - Started process (PID=337) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:03:14.814+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:03:14.816+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:03:14.816+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:03:14.836+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:03:14.833+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:03:14.838+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:03:14.863+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.061 seconds
[2023-04-11T21:03:45.047+0000] {processor.py:154} INFO - Started process (PID=368) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:03:45.049+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:03:45.051+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:03:45.051+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:03:45.077+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:03:45.068+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:03:45.078+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:03:45.102+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.061 seconds
[2023-04-11T21:04:15.173+0000] {processor.py:154} INFO - Started process (PID=398) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:04:15.176+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:04:15.178+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:04:15.178+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:04:15.195+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:04:15.192+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:04:15.196+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:04:15.217+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.051 seconds
[2023-04-11T21:04:45.296+0000] {processor.py:154} INFO - Started process (PID=430) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:04:45.299+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:04:45.301+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:04:45.301+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:04:45.332+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:04:45.315+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:04:45.333+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:04:45.356+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-11T21:05:16.004+0000] {processor.py:154} INFO - Started process (PID=452) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:05:16.008+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:05:16.011+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:05:16.010+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:05:16.031+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:05:16.027+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:05:16.032+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:05:16.068+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-11T21:10:22.440+0000] {processor.py:154} INFO - Started process (PID=471) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:10:22.443+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:10:22.450+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:10:22.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:10:22.469+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:10:22.460+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:10:22.470+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:10:22.491+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.055 seconds
[2023-04-11T21:10:52.845+0000] {processor.py:154} INFO - Started process (PID=501) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:10:52.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:10:52.857+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:10:52.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:10:52.872+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:10:52.869+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:10:52.879+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:10:52.910+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.071 seconds
[2023-04-11T21:11:23.359+0000] {processor.py:154} INFO - Started process (PID=530) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:11:23.368+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:11:23.370+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:11:23.369+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:11:23.395+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:11:23.390+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:11:23.396+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:11:23.421+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.066 seconds
[2023-04-11T21:11:53.557+0000] {processor.py:154} INFO - Started process (PID=553) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:11:53.560+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:11:53.562+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:11:53.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:11:53.583+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:11:53.581+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:11:53.585+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:11:53.607+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.055 seconds
[2023-04-11T21:12:24.164+0000] {processor.py:154} INFO - Started process (PID=583) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:12:24.168+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:12:24.176+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:12:24.175+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:12:24.195+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:12:24.192+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:12:24.196+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:12:24.240+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.084 seconds
[2023-04-11T21:12:54.650+0000] {processor.py:154} INFO - Started process (PID=613) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:12:54.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:12:54.656+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:12:54.656+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:12:54.680+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:12:54.678+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:12:54.688+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:12:54.724+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.081 seconds
[2023-04-11T21:13:25.128+0000] {processor.py:154} INFO - Started process (PID=644) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:13:25.131+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:13:25.132+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:13:25.132+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:13:25.151+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:13:25.148+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:13:25.154+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:13:25.182+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.059 seconds
[2023-04-11T21:13:55.648+0000] {processor.py:154} INFO - Started process (PID=666) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:13:55.651+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:13:55.653+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:13:55.653+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:13:55.695+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:13:55.691+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:13:55.697+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:13:55.731+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-11T21:14:25.774+0000] {processor.py:154} INFO - Started process (PID=698) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:14:25.777+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:14:25.779+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:14:25.779+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:14:25.813+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:14:25.811+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:14:25.816+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:14:25.840+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-11T21:14:55.975+0000] {processor.py:154} INFO - Started process (PID=731) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:14:55.981+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:14:55.989+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:14:55.988+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:14:56.007+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:14:56.004+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:14:56.008+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:14:56.034+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.064 seconds
[2023-04-11T21:15:26.167+0000] {processor.py:154} INFO - Started process (PID=761) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:15:26.169+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:15:26.171+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:15:26.171+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:15:26.203+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:15:26.185+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:15:26.204+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:15:26.224+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.063 seconds
[2023-04-11T21:15:56.290+0000] {processor.py:154} INFO - Started process (PID=783) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:15:56.293+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:15:56.295+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:15:56.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:15:56.326+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:15:56.322+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:15:56.329+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:15:56.357+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-11T21:16:26.569+0000] {processor.py:154} INFO - Started process (PID=814) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:16:26.572+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:16:26.574+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:16:26.574+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:16:26.599+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:16:26.596+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:16:26.600+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:16:26.627+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.066 seconds
[2023-04-11T21:16:57.154+0000] {processor.py:154} INFO - Started process (PID=844) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:16:57.157+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:16:57.159+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:16:57.159+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:16:57.177+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:16:57.174+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:16:57.178+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:16:57.199+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.052 seconds
[2023-04-11T21:20:47.652+0000] {processor.py:154} INFO - Started process (PID=875) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:20:47.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:20:47.666+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:20:47.666+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:20:47.730+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:20:47.724+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:20:47.738+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:20:47.847+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.234 seconds
[2023-04-11T21:21:18.048+0000] {processor.py:154} INFO - Started process (PID=897) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:21:18.051+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:21:18.052+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:21:18.052+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:21:18.067+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:21:18.064+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:21:18.068+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:21:18.104+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.061 seconds
[2023-04-11T21:21:48.351+0000] {processor.py:154} INFO - Started process (PID=928) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:21:48.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:21:48.356+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:21:48.355+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:21:48.372+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:21:48.369+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:21:48.373+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:21:48.394+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.049 seconds
[2023-04-11T21:22:18.875+0000] {processor.py:154} INFO - Started process (PID=961) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:22:18.879+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:22:18.881+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:22:18.881+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:22:18.921+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:22:18.918+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:22:18.923+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:22:18.948+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.079 seconds
[2023-04-11T21:22:49.321+0000] {processor.py:154} INFO - Started process (PID=993) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:22:49.323+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:22:49.325+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:22:49.325+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:22:49.340+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:22:49.337+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:22:49.361+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:22:49.382+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.066 seconds
[2023-04-11T21:26:50.863+0000] {processor.py:154} INFO - Started process (PID=1015) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:26:50.865+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:26:50.866+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:26:50.866+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:26:50.881+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:26:50.879+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:26:50.908+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:26:50.942+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-11T21:50:57.818+0000] {processor.py:154} INFO - Started process (PID=1046) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T21:50:57.820+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T21:50:57.821+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:50:57.821+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T21:50:57.840+0000] {logging_mixin.py:120} INFO - [2023-04-11T21:50:57.838+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T21:50:57.843+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T21:50:57.874+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.059 seconds
[2023-04-11T22:05:16.684+0000] {processor.py:154} INFO - Started process (PID=1075) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:05:16.694+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:05:16.697+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:05:16.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:05:16.802+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:05:16.792+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:05:16.810+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:05:17.140+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.463 seconds
[2023-04-11T22:06:11.727+0000] {processor.py:154} INFO - Started process (PID=1097) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:06:11.731+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:06:11.733+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:06:11.733+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:06:11.756+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:06:11.754+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:06:11.757+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:06:11.786+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-11T22:06:42.304+0000] {processor.py:154} INFO - Started process (PID=1128) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:06:42.306+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:06:42.308+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:06:42.308+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:06:42.322+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:06:42.319+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:06:42.324+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:06:42.347+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.048 seconds
[2023-04-11T22:07:12.634+0000] {processor.py:154} INFO - Started process (PID=1158) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:07:12.638+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:07:12.640+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:07:12.640+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:07:12.664+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:07:12.659+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:07:12.694+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:07:12.758+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.130 seconds
[2023-04-11T22:07:43.243+0000] {processor.py:154} INFO - Started process (PID=1181) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:07:43.255+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:07:43.258+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:07:43.257+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:07:43.284+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:07:43.280+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:07:43.286+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:07:43.320+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.099 seconds
[2023-04-11T22:08:13.804+0000] {processor.py:154} INFO - Started process (PID=1212) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:08:13.807+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:08:13.809+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:08:13.809+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:08:13.830+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:08:13.828+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:08:13.832+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:08:13.858+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.060 seconds
[2023-04-11T22:08:44.125+0000] {processor.py:154} INFO - Started process (PID=1243) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:08:44.133+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:08:44.135+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:08:44.135+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:08:44.161+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:08:44.157+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:08:44.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:08:44.191+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.079 seconds
[2023-04-11T22:20:18.121+0000] {processor.py:154} INFO - Started process (PID=1266) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:20:18.123+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:20:18.125+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:20:18.125+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:20:18.141+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:20:18.138+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:20:18.142+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:20:18.179+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.065 seconds
[2023-04-11T22:23:46.703+0000] {processor.py:154} INFO - Started process (PID=1298) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:23:46.710+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:23:46.717+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:23:46.717+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:23:46.772+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:23:46.760+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:23:46.781+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:23:46.859+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.165 seconds
[2023-04-11T22:24:17.226+0000] {processor.py:154} INFO - Started process (PID=1328) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:24:17.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:24:17.234+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:24:17.234+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:24:17.260+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:24:17.257+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:24:17.263+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:24:17.287+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-11T22:24:47.396+0000] {processor.py:154} INFO - Started process (PID=1350) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:24:47.399+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:24:47.401+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:24:47.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:24:47.437+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:24:47.434+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:24:47.438+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:24:47.460+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-11T22:25:17.607+0000] {processor.py:154} INFO - Started process (PID=1381) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:25:17.610+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:25:17.612+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:25:17.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:25:17.650+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:25:17.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:25:17.652+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:25:17.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-11T22:25:47.739+0000] {processor.py:154} INFO - Started process (PID=1414) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:25:47.741+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:25:47.742+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:25:47.742+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:25:47.760+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:25:47.758+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:25:47.762+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:25:47.788+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.053 seconds
[2023-04-11T22:26:17.854+0000] {processor.py:154} INFO - Started process (PID=1445) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:26:17.857+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:26:17.859+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:26:17.859+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:26:17.891+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:26:17.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:26:17.892+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:26:17.917+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.068 seconds
[2023-04-11T22:26:48.381+0000] {processor.py:154} INFO - Started process (PID=1473) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:26:48.384+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:26:48.386+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:26:48.386+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:26:48.443+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:26:48.432+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:26:48.446+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:26:48.474+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.102 seconds
[2023-04-11T22:27:18.590+0000] {processor.py:154} INFO - Started process (PID=1498) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:27:18.592+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:27:18.594+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:27:18.593+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:27:18.608+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:27:18.606+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:27:18.609+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:27:18.631+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.045 seconds
[2023-04-11T22:27:49.214+0000] {processor.py:154} INFO - Started process (PID=1528) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:27:49.217+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:27:49.219+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:27:49.219+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:27:49.233+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:27:49.231+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:27:49.235+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:27:49.284+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-11T22:28:19.367+0000] {processor.py:154} INFO - Started process (PID=1560) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:28:19.371+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:28:19.373+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:28:19.373+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:28:19.403+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:28:19.400+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:28:19.406+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:28:19.448+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-11T22:28:50.076+0000] {processor.py:154} INFO - Started process (PID=1592) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:28:50.078+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:28:50.080+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:28:50.080+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:28:50.102+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:28:50.099+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:28:50.104+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:28:50.128+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.059 seconds
[2023-04-11T22:29:20.257+0000] {processor.py:154} INFO - Started process (PID=1614) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:29:20.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:29:20.261+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:29:20.261+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:29:20.290+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:29:20.275+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:29:20.292+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:29:20.332+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.082 seconds
[2023-04-11T22:30:41.260+0000] {processor.py:154} INFO - Started process (PID=1647) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:30:41.277+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:30:41.285+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:30:41.285+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:30:41.565+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:30:41.540+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:30:41.624+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:30:41.788+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.537 seconds
[2023-04-11T22:31:11.892+0000] {processor.py:154} INFO - Started process (PID=1677) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:31:11.895+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:31:11.896+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:31:11.896+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:31:11.915+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:31:11.913+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:31:11.916+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:31:11.937+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.052 seconds
[2023-04-11T22:31:42.340+0000] {processor.py:154} INFO - Started process (PID=1699) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:31:42.343+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:31:42.344+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:31:42.344+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:31:42.366+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:31:42.364+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:31:42.367+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:31:42.392+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.057 seconds
[2023-04-11T22:32:12.580+0000] {processor.py:154} INFO - Started process (PID=1730) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:32:12.583+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:32:12.584+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:32:12.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:32:12.625+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:32:12.618+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:32:12.628+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:32:12.655+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.079 seconds
[2023-04-11T22:32:43.144+0000] {processor.py:154} INFO - Started process (PID=1761) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:32:43.146+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:32:43.148+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:32:43.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:32:43.161+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:32:43.159+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:32:43.162+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:32:43.196+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.056 seconds
[2023-04-11T22:33:13.308+0000] {processor.py:154} INFO - Started process (PID=1793) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:33:13.311+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:33:13.313+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:33:13.313+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:33:13.333+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:33:13.331+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:33:13.341+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:33:13.371+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-11T22:33:43.779+0000] {processor.py:154} INFO - Started process (PID=1825) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:33:43.786+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:33:43.788+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:33:43.788+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:33:43.811+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:33:43.803+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:33:43.814+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:33:43.842+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.076 seconds
[2023-04-11T22:34:13.956+0000] {processor.py:154} INFO - Started process (PID=1848) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:34:13.958+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:34:13.960+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:34:13.959+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:34:13.975+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:34:13.973+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:34:13.976+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:34:13.999+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.048 seconds
[2023-04-11T22:34:44.534+0000] {processor.py:154} INFO - Started process (PID=1877) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:34:44.538+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:34:44.540+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:34:44.540+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:34:44.557+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:34:44.555+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:34:44.558+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:34:44.580+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.053 seconds
[2023-04-11T22:35:14.642+0000] {processor.py:154} INFO - Started process (PID=1907) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:35:14.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:35:14.647+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:35:14.646+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:35:14.663+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:35:14.661+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:35:14.666+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:35:14.689+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.054 seconds
[2023-04-11T22:35:45.341+0000] {processor.py:154} INFO - Started process (PID=1937) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:35:45.344+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:35:45.346+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:35:45.346+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:35:45.362+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:35:45.359+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:35:45.363+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:35:45.394+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.060 seconds
[2023-04-11T22:36:15.774+0000] {processor.py:154} INFO - Started process (PID=1967) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:36:15.777+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:36:15.784+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:36:15.784+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:36:15.803+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:36:15.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:36:15.805+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:36:15.840+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.071 seconds
[2023-04-11T22:36:46.260+0000] {processor.py:154} INFO - Started process (PID=1987) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:36:46.267+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:36:46.270+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:36:46.270+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:36:46.291+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:36:46.288+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:36:46.293+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:36:46.323+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-11T22:37:16.766+0000] {processor.py:154} INFO - Started process (PID=2018) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:37:16.770+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:37:16.772+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:37:16.772+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:37:16.796+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:37:16.794+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:37:16.798+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:37:16.823+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.065 seconds
[2023-04-11T22:37:46.904+0000] {processor.py:154} INFO - Started process (PID=2048) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:37:46.907+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:37:46.908+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:37:46.908+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:37:46.923+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:37:46.920+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:37:46.924+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:37:46.950+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.050 seconds
[2023-04-11T22:38:17.086+0000] {processor.py:154} INFO - Started process (PID=2078) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:38:17.090+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:38:17.091+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:38:17.091+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:38:17.129+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:38:17.126+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:38:17.132+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:38:17.159+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.081 seconds
[2023-04-11T22:38:47.632+0000] {processor.py:154} INFO - Started process (PID=2101) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:38:47.635+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:38:47.636+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:38:47.636+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:38:47.652+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:38:47.649+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:38:47.653+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:38:47.676+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.051 seconds
[2023-04-11T22:39:17.845+0000] {processor.py:154} INFO - Started process (PID=2132) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:39:17.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:39:17.850+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:39:17.850+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:39:17.868+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:39:17.866+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:39:17.870+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:39:17.896+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.056 seconds
[2023-04-11T22:39:48.501+0000] {processor.py:154} INFO - Started process (PID=2163) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:39:48.504+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:39:48.505+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:39:48.505+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:39:48.522+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:39:48.520+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:39:48.524+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:39:48.561+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.066 seconds
[2023-04-11T22:40:18.990+0000] {processor.py:154} INFO - Started process (PID=2193) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:40:18.993+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:40:18.995+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:40:18.995+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:40:19.019+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:40:19.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:40:19.021+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:40:19.057+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.073 seconds
[2023-04-11T22:40:49.186+0000] {processor.py:154} INFO - Started process (PID=2216) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:40:49.189+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:40:49.194+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:40:49.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:40:49.210+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:40:49.208+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:40:49.211+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:40:49.241+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.062 seconds
[2023-04-11T22:41:19.596+0000] {processor.py:154} INFO - Started process (PID=2246) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:41:19.599+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:41:19.602+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:41:19.602+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:41:19.630+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:41:19.626+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:41:19.632+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:41:19.667+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.077 seconds
[2023-04-11T22:41:49.844+0000] {processor.py:154} INFO - Started process (PID=2276) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:41:49.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:41:49.850+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:41:49.849+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:41:49.872+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:41:49.869+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:41:49.873+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:41:49.904+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.066 seconds
[2023-04-11T22:42:20.071+0000] {processor.py:154} INFO - Started process (PID=2307) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:42:20.074+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:42:20.097+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:42:20.097+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:42:20.112+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:42:20.110+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:42:20.114+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:42:20.137+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.072 seconds
[2023-04-11T22:42:50.446+0000] {processor.py:154} INFO - Started process (PID=2329) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:42:50.461+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:42:50.464+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:42:50.464+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:42:50.496+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:42:50.493+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:42:50.498+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:42:50.526+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-11T22:43:21.016+0000] {processor.py:154} INFO - Started process (PID=2360) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:43:21.020+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:43:21.021+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:43:21.021+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:43:21.050+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:43:21.045+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:43:21.051+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:43:21.079+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-11T22:43:51.291+0000] {processor.py:154} INFO - Started process (PID=2390) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:43:51.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:43:51.297+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:43:51.296+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:43:51.326+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:43:51.324+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:43:51.327+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:43:51.353+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-11T22:44:21.424+0000] {processor.py:154} INFO - Started process (PID=2420) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:44:21.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:44:21.428+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:44:21.428+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:44:21.442+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:44:21.440+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:44:21.447+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:44:21.473+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.054 seconds
[2023-04-11T22:44:51.769+0000] {processor.py:154} INFO - Started process (PID=2448) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:44:51.775+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:44:52.121+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:44:52.103+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:44:52.244+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:44:52.234+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:44:52.269+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:44:52.425+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.674 seconds
[2023-04-11T22:46:00.750+0000] {processor.py:154} INFO - Started process (PID=2461) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T22:46:00.758+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T22:46:00.760+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:46:00.759+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T22:46:00.776+0000] {logging_mixin.py:120} INFO - [2023-04-11T22:46:00.773+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T22:46:00.777+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T22:46:00.823+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.082 seconds
[2023-04-11T23:50:34.226+0000] {processor.py:154} INFO - Started process (PID=2491) to work on /opt/airflow/dags/snow_air.py
[2023-04-11T23:50:34.229+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-11T23:50:34.231+0000] {logging_mixin.py:120} INFO - [2023-04-11T23:50:34.231+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-11T23:50:34.258+0000] {logging_mixin.py:120} INFO - [2023-04-11T23:50:34.255+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-11T23:50:34.261+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-11T23:50:34.308+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.087 seconds
