[2023-04-09T00:28:43.125+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.store_user manual__2023-04-09T00:26:53.028134+00:00 [queued]>
[2023-04-09T00:28:43.136+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: api_dag.store_user manual__2023-04-09T00:26:53.028134+00:00 [queued]>
[2023-04-09T00:28:43.137+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T00:28:43.138+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-04-09T00:28:43.138+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T00:28:43.146+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-04-09 00:26:53.028134+00:00
[2023-04-09T00:28:43.154+0000] {standard_task_runner.py:55} INFO - Started process 9440 to run task
[2023-04-09T00:28:43.159+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'store_user', 'manual__2023-04-09T00:26:53.028134+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmp15pkc2m2']
[2023-04-09T00:28:43.166+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask store_user
[2023-04-09T00:28:43.230+0000] {task_command.py:376} INFO - Running <TaskInstance: api_dag.store_user manual__2023-04-09T00:26:53.028134+00:00 [running]> on host c12a518d534c
[2023-04-09T00:28:43.282+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-04-09T00:26:53.028134+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-09T00:26:53.028134+00:00
[2023-04-09T00:28:43.285+0000] {postgres.py:129} INFO - Running copy expert: COPY user_details FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-04-09T00:28:43.295+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-09T00:28:43.303+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api.py", line 15, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "country"
CONTEXT:  COPY user_details, line 1: "Bela,Heinlein"

[2023-04-09T00:28:43.314+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=api_dag, task_id=store_user, execution_date=20230409T002653, start_date=20230409T002843, end_date=20230409T002843
[2023-04-09T00:28:43.321+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 50 for task store_user (missing data for column "country"
CONTEXT:  COPY user_details, line 1: "Bela,Heinlein"
; 9440)
[2023-04-09T00:28:43.375+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-04-09T00:28:43.392+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
