[2023-04-16T00:02:14.469+0000] {processor.py:154} INFO - Started process (PID=62390) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:02:14.473+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:02:14.475+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:02:14.475+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:02:14.588+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:02:14.548+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:02:14.592+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:02:14.675+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.222 seconds
[2023-04-16T00:04:34.615+0000] {processor.py:154} INFO - Started process (PID=62412) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:04:34.621+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:04:34.623+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:04:34.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:04:34.693+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:04:34.654+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:04:34.697+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:04:34.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.125 seconds
[2023-04-16T00:05:05.408+0000] {processor.py:154} INFO - Started process (PID=62445) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:05:05.411+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:05:05.413+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:05:05.413+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:05:05.451+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:05:05.440+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:05:05.454+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:05:05.499+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.099 seconds
[2023-04-16T00:05:35.657+0000] {processor.py:154} INFO - Started process (PID=62476) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:05:35.660+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:05:35.661+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:05:35.661+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:05:35.681+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:05:35.677+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:05:35.685+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:05:35.719+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-16T00:06:06.061+0000] {processor.py:154} INFO - Started process (PID=62499) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:06:06.065+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:06:06.067+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:06:06.067+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:06:06.091+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:06:06.084+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:06:06.092+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:06:06.134+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-16T00:06:36.487+0000] {processor.py:154} INFO - Started process (PID=62530) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:06:36.490+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:06:36.492+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:06:36.492+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:06:36.528+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:06:36.518+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:06:36.537+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:06:36.593+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.115 seconds
[2023-04-16T00:07:06.704+0000] {processor.py:154} INFO - Started process (PID=62562) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:07:06.708+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:07:06.710+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:07:06.710+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:07:06.731+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:07:06.726+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:07:06.733+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:07:06.770+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.073 seconds
[2023-04-16T00:07:37.206+0000] {processor.py:154} INFO - Started process (PID=62592) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:07:37.209+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:07:37.211+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:07:37.211+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:07:37.236+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:07:37.233+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:07:37.244+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:07:37.275+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-16T00:08:07.546+0000] {processor.py:154} INFO - Started process (PID=62614) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:08:07.550+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:08:07.552+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:08:07.552+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:08:07.588+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:08:07.585+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:08:07.590+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:08:07.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.081 seconds
[2023-04-16T00:08:38.184+0000] {processor.py:154} INFO - Started process (PID=62645) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:08:38.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:08:38.194+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:08:38.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:08:38.218+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:08:38.215+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:08:38.219+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:08:38.264+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.093 seconds
[2023-04-16T00:11:21.351+0000] {processor.py:154} INFO - Started process (PID=62675) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:11:21.452+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:11:21.475+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:11:21.475+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:11:21.593+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:11:21.586+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:11:21.604+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:11:21.689+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.373 seconds
[2023-04-16T00:11:52.281+0000] {processor.py:154} INFO - Started process (PID=62697) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:11:52.284+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:11:52.287+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:11:52.287+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:11:52.310+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:11:52.307+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:11:52.311+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:11:52.339+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-16T00:12:22.816+0000] {processor.py:154} INFO - Started process (PID=62728) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:12:22.821+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:12:22.823+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:12:22.822+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:12:22.852+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:12:22.848+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:12:22.853+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:12:22.900+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.094 seconds
[2023-04-16T00:12:53.168+0000] {processor.py:154} INFO - Started process (PID=62759) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:12:53.174+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:12:53.177+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:12:53.176+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:12:53.201+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:12:53.198+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:12:53.203+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:12:53.247+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.090 seconds
[2023-04-16T00:13:23.598+0000] {processor.py:154} INFO - Started process (PID=62781) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:13:23.602+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:13:23.604+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:13:23.604+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:13:23.658+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:13:23.650+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:13:23.660+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:13:23.694+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.102 seconds
[2023-04-16T00:13:53.891+0000] {processor.py:154} INFO - Started process (PID=62811) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:13:53.895+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:13:53.898+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:13:53.898+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:13:53.941+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:13:53.937+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:13:53.951+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:13:53.989+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.108 seconds
[2023-04-16T00:14:24.541+0000] {processor.py:154} INFO - Started process (PID=62841) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:14:24.544+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:14:24.546+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:14:24.545+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:14:24.582+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:14:24.578+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:14:24.586+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:14:24.622+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-16T00:14:54.916+0000] {processor.py:154} INFO - Started process (PID=62871) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:14:54.929+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:14:54.932+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:14:54.932+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:14:54.954+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:14:54.952+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:14:54.962+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:14:54.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.084 seconds
[2023-04-16T00:15:25.343+0000] {processor.py:154} INFO - Started process (PID=62894) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:15:25.347+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:15:25.349+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:15:25.349+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:15:25.379+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:15:25.376+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:15:25.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:15:25.410+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.079 seconds
[2023-04-16T00:32:07.874+0000] {processor.py:154} INFO - Started process (PID=62926) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:32:07.915+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:32:07.948+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:32:07.943+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:32:08.501+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:32:08.410+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:32:08.524+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:32:09.142+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 1.325 seconds
[2023-04-16T00:37:11.912+0000] {processor.py:154} INFO - Started process (PID=62948) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:37:11.915+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:37:11.918+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:37:11.918+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:37:11.943+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:37:11.941+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:37:11.945+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:37:12.016+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.110 seconds
[2023-04-16T00:37:42.456+0000] {processor.py:154} INFO - Started process (PID=62980) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:37:42.459+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:37:42.463+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:37:42.462+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:37:42.498+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:37:42.495+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:37:42.500+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:37:42.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.112 seconds
[2023-04-16T00:38:12.758+0000] {processor.py:154} INFO - Started process (PID=63010) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:38:12.761+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:38:12.762+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:38:12.762+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:38:12.781+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:38:12.778+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:38:12.782+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:38:12.821+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-16T00:38:42.958+0000] {processor.py:154} INFO - Started process (PID=63031) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:38:42.961+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:38:42.962+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:38:42.962+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:38:42.979+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:38:42.976+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:38:42.984+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:38:43.033+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.083 seconds
[2023-04-16T00:39:13.671+0000] {processor.py:154} INFO - Started process (PID=63062) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:39:13.674+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:39:13.681+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:39:13.681+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:39:13.702+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:39:13.699+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:39:13.737+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:39:13.782+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.116 seconds
[2023-04-16T00:39:43.961+0000] {processor.py:154} INFO - Started process (PID=63093) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:39:43.963+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:39:43.966+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:39:43.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:39:43.998+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:39:43.994+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:39:44.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:39:44.046+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.092 seconds
[2023-04-16T00:40:14.241+0000] {processor.py:154} INFO - Started process (PID=63124) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:40:14.245+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:40:14.248+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:40:14.248+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:40:14.282+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:40:14.279+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:40:14.284+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:40:14.333+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.107 seconds
[2023-04-16T00:40:45.316+0000] {processor.py:154} INFO - Started process (PID=63148) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:40:45.319+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:40:45.321+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:40:45.320+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:40:45.340+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:40:45.336+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:40:45.342+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:40:45.368+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.068 seconds
[2023-04-16T00:41:15.548+0000] {processor.py:154} INFO - Started process (PID=63180) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:41:15.551+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:41:15.554+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:41:15.554+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:41:15.574+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:41:15.567+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:41:15.575+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:41:15.612+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-16T00:41:45.953+0000] {processor.py:154} INFO - Started process (PID=63211) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:41:45.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:41:45.959+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:41:45.959+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:41:45.980+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:41:45.977+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:41:45.989+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:41:46.038+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.092 seconds
[2023-04-16T00:42:16.306+0000] {processor.py:154} INFO - Started process (PID=63242) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:42:16.309+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:42:16.311+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:42:16.311+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:42:16.329+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:42:16.327+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:42:16.330+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:42:16.353+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.052 seconds
[2023-04-16T00:42:46.804+0000] {processor.py:154} INFO - Started process (PID=63263) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:42:46.810+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:42:46.815+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:42:46.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:42:46.890+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:42:46.886+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:42:46.891+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:42:46.944+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.146 seconds
[2023-04-16T00:43:17.294+0000] {processor.py:154} INFO - Started process (PID=63295) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:43:17.296+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:43:17.298+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:43:17.298+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:43:17.317+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:43:17.314+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:43:17.318+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:43:17.365+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.076 seconds
[2023-04-16T00:43:47.750+0000] {processor.py:154} INFO - Started process (PID=63325) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:43:47.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:43:47.786+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:43:47.786+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:43:47.801+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:43:47.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:43:47.802+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:43:47.832+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-16T00:44:18.105+0000] {processor.py:154} INFO - Started process (PID=63357) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:44:18.107+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:44:18.109+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:44:18.109+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:44:18.136+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:44:18.133+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:44:18.138+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:44:18.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-16T00:44:48.452+0000] {processor.py:154} INFO - Started process (PID=63379) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:44:48.455+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:44:48.457+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:44:48.457+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:44:48.472+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:44:48.470+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:44:48.473+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:44:48.520+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-16T00:45:18.692+0000] {processor.py:154} INFO - Started process (PID=63409) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:45:18.696+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:45:18.697+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:45:18.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:45:18.742+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:45:18.738+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:45:18.743+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:45:18.771+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-16T00:45:49.064+0000] {processor.py:154} INFO - Started process (PID=63440) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:45:49.068+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:45:49.070+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:45:49.070+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:45:49.115+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:45:49.113+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:45:49.117+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:45:49.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.093 seconds
[2023-04-16T00:46:19.653+0000] {processor.py:154} INFO - Started process (PID=63471) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:46:19.656+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:46:19.666+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:46:19.666+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:46:19.683+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:46:19.681+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:46:19.691+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:46:19.716+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.070 seconds
[2023-04-16T00:46:49.886+0000] {processor.py:154} INFO - Started process (PID=63501) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:46:49.890+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:46:49.892+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:46:49.892+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:46:49.922+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:46:49.915+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:46:49.964+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:46:49.996+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.115 seconds
[2023-04-16T00:47:20.194+0000] {processor.py:154} INFO - Started process (PID=63523) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:47:20.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:47:20.198+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:47:20.198+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:47:20.212+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:47:20.210+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:47:20.213+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:47:20.235+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.046 seconds
[2023-04-16T00:47:50.533+0000] {processor.py:154} INFO - Started process (PID=63554) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:47:50.536+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:47:50.538+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:47:50.538+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:47:50.561+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:47:50.559+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:47:50.563+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:47:50.615+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-16T00:48:20.960+0000] {processor.py:154} INFO - Started process (PID=63584) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:48:20.963+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:48:20.965+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:48:20.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:48:20.992+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:48:20.988+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:48:20.994+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:48:21.027+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-16T00:48:51.387+0000] {processor.py:154} INFO - Started process (PID=63618) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:48:51.390+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:48:51.391+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:48:51.391+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:48:51.408+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:48:51.406+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:48:51.409+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:48:51.433+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.050 seconds
[2023-04-16T00:49:21.672+0000] {processor.py:154} INFO - Started process (PID=63640) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:49:21.675+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:49:21.677+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:49:21.677+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:49:21.693+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:49:21.691+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:49:21.695+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:49:21.736+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.073 seconds
[2023-04-16T00:49:52.196+0000] {processor.py:154} INFO - Started process (PID=63669) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:49:52.199+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:49:52.201+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:49:52.201+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:49:52.234+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:49:52.229+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:49:52.236+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:49:52.266+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.075 seconds
[2023-04-16T00:50:22.614+0000] {processor.py:154} INFO - Started process (PID=63700) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:50:22.618+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:50:22.620+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:50:22.620+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:50:22.640+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:50:22.638+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:50:22.642+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:50:22.674+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.066 seconds
[2023-04-16T00:50:52.936+0000] {processor.py:154} INFO - Started process (PID=63731) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:50:52.939+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:50:52.941+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:50:52.940+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:50:52.956+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:50:52.953+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:50:52.957+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:50:52.984+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.055 seconds
[2023-04-16T00:51:23.122+0000] {processor.py:154} INFO - Started process (PID=63753) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:51:23.125+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:51:23.136+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:51:23.136+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:51:23.181+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:51:23.177+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:51:23.183+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:51:23.248+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.130 seconds
[2023-04-16T00:51:53.611+0000] {processor.py:154} INFO - Started process (PID=63784) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:51:53.614+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:51:53.615+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:51:53.615+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:51:53.675+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:51:53.672+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:51:53.677+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:51:53.708+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.101 seconds
[2023-04-16T00:52:23.993+0000] {processor.py:154} INFO - Started process (PID=63815) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:52:23.998+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:52:24.009+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:52:24.009+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:52:24.079+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:52:24.075+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:52:24.081+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:52:24.131+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.146 seconds
[2023-04-16T00:52:55.631+0000] {processor.py:154} INFO - Started process (PID=63846) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:52:55.664+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:52:55.671+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:52:55.670+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:52:55.828+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:52:55.808+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:52:55.832+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:52:55.995+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.580 seconds
[2023-04-16T00:53:26.805+0000] {processor.py:154} INFO - Started process (PID=63865) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:53:26.812+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:53:26.814+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:53:26.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:53:26.855+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:53:26.851+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:53:26.856+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:53:26.895+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.096 seconds
[2023-04-16T00:53:57.260+0000] {processor.py:154} INFO - Started process (PID=63895) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:53:57.263+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:53:57.266+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:53:57.266+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:53:57.285+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:53:57.282+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:53:57.315+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:53:57.340+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-16T00:54:27.463+0000] {processor.py:154} INFO - Started process (PID=63927) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:54:27.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:54:27.467+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:54:27.467+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:54:27.526+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:54:27.524+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:54:27.529+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:54:27.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.100 seconds
[2023-04-16T00:54:57.809+0000] {processor.py:154} INFO - Started process (PID=63960) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:54:57.812+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:54:57.815+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:54:57.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:54:57.835+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:54:57.831+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:54:57.838+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:54:57.894+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.095 seconds
[2023-04-16T00:55:28.065+0000] {processor.py:154} INFO - Started process (PID=63981) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:55:28.067+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:55:28.069+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:55:28.069+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:55:28.094+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:55:28.092+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:55:28.096+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:55:28.144+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.085 seconds
[2023-04-16T00:55:58.704+0000] {processor.py:154} INFO - Started process (PID=64010) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:55:58.708+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:55:58.709+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:55:58.709+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:55:58.736+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:55:58.734+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:55:58.739+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:55:58.786+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.089 seconds
[2023-04-16T00:56:29.010+0000] {processor.py:154} INFO - Started process (PID=64041) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:56:29.013+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:56:29.014+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:56:29.014+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:56:29.039+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:56:29.032+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:56:29.050+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:56:29.077+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.072 seconds
[2023-04-16T00:56:59.335+0000] {processor.py:154} INFO - Started process (PID=64072) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:56:59.338+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:56:59.342+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:56:59.342+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:56:59.364+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:56:59.360+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:56:59.366+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:56:59.418+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.109 seconds
[2023-04-16T00:57:29.850+0000] {processor.py:154} INFO - Started process (PID=64095) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:57:29.857+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:57:29.859+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:57:29.858+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:57:29.878+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:57:29.873+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:57:29.880+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:57:29.903+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.058 seconds
[2023-04-16T00:58:00.174+0000] {processor.py:154} INFO - Started process (PID=64126) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:58:00.176+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:58:00.180+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:58:00.180+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:58:00.196+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:58:00.194+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:58:00.198+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:58:00.234+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.065 seconds
[2023-04-16T00:58:30.343+0000] {processor.py:154} INFO - Started process (PID=64157) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:58:30.346+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:58:30.355+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:58:30.355+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:58:30.385+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:58:30.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:58:30.394+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:58:30.423+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-16T00:59:00.625+0000] {processor.py:154} INFO - Started process (PID=64188) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:59:00.629+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:59:00.631+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:59:00.630+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:59:00.659+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:59:00.655+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:59:00.678+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:59:00.726+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.107 seconds
[2023-04-16T00:59:31.094+0000] {processor.py:154} INFO - Started process (PID=64210) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T00:59:31.096+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T00:59:31.102+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:59:31.101+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T00:59:31.119+0000] {logging_mixin.py:120} INFO - [2023-04-16T00:59:31.116+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T00:59:31.150+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T00:59:31.196+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.109 seconds
[2023-04-16T01:00:01.620+0000] {processor.py:154} INFO - Started process (PID=64241) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:00:01.626+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:00:01.629+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:00:01.629+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:00:01.661+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:00:01.658+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:00:01.662+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:00:01.690+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.079 seconds
[2023-04-16T01:00:32.006+0000] {processor.py:154} INFO - Started process (PID=64272) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:00:32.009+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:00:32.011+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:00:32.010+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:00:32.034+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:00:32.031+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:00:32.037+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:00:32.062+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.062 seconds
[2023-04-16T01:01:02.356+0000] {processor.py:154} INFO - Started process (PID=64302) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:01:02.364+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:01:02.366+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:01:02.366+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:01:02.387+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:01:02.383+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:01:02.389+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:01:02.439+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-16T01:01:33.009+0000] {processor.py:154} INFO - Started process (PID=64324) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:01:33.038+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:01:33.040+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:01:33.040+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:01:33.058+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:01:33.055+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:01:33.060+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:01:33.088+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-16T01:02:03.548+0000] {processor.py:154} INFO - Started process (PID=64355) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:02:03.550+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:02:03.551+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:02:03.551+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:02:03.580+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:02:03.578+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:02:03.583+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:02:03.623+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.081 seconds
[2023-04-16T01:02:34.096+0000] {processor.py:154} INFO - Started process (PID=64388) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:02:34.098+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:02:34.100+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:02:34.100+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:02:34.143+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:02:34.140+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:02:34.144+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:02:34.167+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.076 seconds
[2023-04-16T01:03:04.339+0000] {processor.py:154} INFO - Started process (PID=64418) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:03:04.345+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:03:04.350+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:03:04.349+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:03:04.430+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:03:04.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:03:04.434+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:03:04.475+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.145 seconds
[2023-04-16T01:03:34.660+0000] {processor.py:154} INFO - Started process (PID=64440) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:03:34.662+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:03:34.664+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:03:34.664+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:03:34.680+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:03:34.678+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:03:34.682+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:03:34.720+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.064 seconds
[2023-04-16T01:04:04.920+0000] {processor.py:154} INFO - Started process (PID=64470) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:04:04.922+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:04:04.923+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:04:04.923+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:04:04.946+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:04:04.943+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:04:04.947+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:04:04.988+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.076 seconds
[2023-04-16T01:04:35.227+0000] {processor.py:154} INFO - Started process (PID=64501) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:04:35.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:04:35.232+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:04:35.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:04:35.252+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:04:35.249+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:04:35.253+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:04:35.277+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.057 seconds
[2023-04-16T01:05:05.720+0000] {processor.py:154} INFO - Started process (PID=64523) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:05:05.723+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:05:05.725+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:05:05.725+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:05:05.756+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:05:05.753+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:05:05.758+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:05:05.787+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-16T01:05:36.347+0000] {processor.py:154} INFO - Started process (PID=64554) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:05:36.350+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:05:36.394+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:05:36.393+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:05:36.412+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:05:36.409+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:05:36.414+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:05:36.446+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.105 seconds
[2023-04-16T01:06:07.066+0000] {processor.py:154} INFO - Started process (PID=64584) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:06:07.072+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:06:07.080+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:06:07.079+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:06:07.109+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:06:07.106+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:06:07.110+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:06:07.145+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-16T01:06:37.834+0000] {processor.py:154} INFO - Started process (PID=64615) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:06:37.839+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:06:37.852+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:06:37.851+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:06:37.899+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:06:37.893+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:06:37.902+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:06:37.955+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.129 seconds
[2023-04-16T01:07:08.222+0000] {processor.py:154} INFO - Started process (PID=64636) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:07:08.225+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:07:08.226+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:07:08.226+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:07:08.276+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:07:08.274+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:07:08.278+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:07:08.305+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.088 seconds
[2023-04-16T01:07:38.460+0000] {processor.py:154} INFO - Started process (PID=64667) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:07:38.463+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:07:38.464+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:07:38.464+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:07:38.483+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:07:38.481+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:07:38.485+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:07:38.512+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.069 seconds
[2023-04-16T01:08:08.903+0000] {processor.py:154} INFO - Started process (PID=64698) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:08:08.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:08:08.906+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:08:08.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:08:08.921+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:08:08.918+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:08:08.923+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:08:08.962+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.064 seconds
[2023-04-16T01:08:39.354+0000] {processor.py:154} INFO - Started process (PID=64730) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:08:39.359+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:08:39.363+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:08:39.363+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:08:39.433+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:08:39.423+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:08:39.435+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:08:39.494+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.146 seconds
[2023-04-16T01:09:09.661+0000] {processor.py:154} INFO - Started process (PID=64752) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:09:09.664+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:09:09.666+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:09:09.666+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:09:09.713+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:09:09.711+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:09:09.715+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:09:09.737+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.081 seconds
[2023-04-16T01:09:40.057+0000] {processor.py:154} INFO - Started process (PID=64782) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:09:40.059+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:09:40.060+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:09:40.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:09:40.077+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:09:40.075+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:09:40.086+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:09:40.104+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.052 seconds
[2023-04-16T01:10:10.441+0000] {processor.py:154} INFO - Started process (PID=64811) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:10:10.445+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:10:10.446+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:10:10.446+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:10:10.469+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:10:10.467+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:10:10.477+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:10:10.503+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-16T01:10:40.645+0000] {processor.py:154} INFO - Started process (PID=64833) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:10:40.648+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:10:40.650+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:10:40.649+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:10:40.680+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:10:40.677+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:10:40.681+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:10:40.713+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.072 seconds
[2023-04-16T01:11:11.240+0000] {processor.py:154} INFO - Started process (PID=64864) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:11:11.242+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:11:11.244+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:11:11.244+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:11:11.260+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:11:11.257+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:11:11.262+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:11:11.285+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.051 seconds
[2023-04-16T01:11:41.663+0000] {processor.py:154} INFO - Started process (PID=64894) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:11:41.668+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:11:41.670+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:11:41.669+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:11:41.697+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:11:41.687+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:11:41.698+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:11:41.746+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.091 seconds
[2023-04-16T01:12:12.046+0000] {processor.py:154} INFO - Started process (PID=64925) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:12:12.049+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:12:12.051+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:12:12.051+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:12:12.065+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:12:12.063+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:12:12.067+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:12:12.089+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.048 seconds
[2023-04-16T01:12:42.558+0000] {processor.py:154} INFO - Started process (PID=64948) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:12:42.561+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:12:42.562+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:12:42.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:12:42.599+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:12:42.576+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:12:42.601+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:12:42.629+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.076 seconds
[2023-04-16T01:13:12.777+0000] {processor.py:154} INFO - Started process (PID=64979) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:13:12.780+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:13:12.791+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:13:12.791+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:13:12.808+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:13:12.806+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:13:12.809+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:13:12.842+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.073 seconds
[2023-04-16T01:13:43.332+0000] {processor.py:154} INFO - Started process (PID=65010) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:13:43.335+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:13:43.336+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:13:43.336+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:13:43.353+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:13:43.350+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:13:43.356+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:13:43.381+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.055 seconds
[2023-04-16T01:14:13.818+0000] {processor.py:154} INFO - Started process (PID=65041) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:14:13.822+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:14:13.827+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:14:13.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:14:13.882+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:14:13.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:14:13.886+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:14:13.940+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.133 seconds
[2023-04-16T01:14:44.051+0000] {processor.py:154} INFO - Started process (PID=65063) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:14:44.053+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:14:44.055+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:14:44.055+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:14:44.070+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:14:44.067+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:14:44.071+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:14:44.115+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.068 seconds
[2023-04-16T01:15:14.526+0000] {processor.py:154} INFO - Started process (PID=65096) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:15:14.530+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:15:14.533+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:15:14.533+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:15:14.559+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:15:14.556+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:15:14.561+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:15:14.613+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.093 seconds
[2023-04-16T01:15:44.801+0000] {processor.py:154} INFO - Started process (PID=65125) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:15:44.804+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:15:44.808+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:15:44.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:15:44.825+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:15:44.823+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:15:44.856+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:15:44.885+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.091 seconds
[2023-04-16T01:16:15.229+0000] {processor.py:154} INFO - Started process (PID=65147) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:16:15.258+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:16:15.261+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:16:15.260+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:16:15.299+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:16:15.295+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:16:15.309+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:16:15.358+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.142 seconds
[2023-04-16T01:16:45.927+0000] {processor.py:154} INFO - Started process (PID=65177) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:16:45.929+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:16:45.931+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:16:45.931+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:16:45.955+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:16:45.953+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:16:45.963+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:16:45.992+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.071 seconds
[2023-04-16T01:17:16.445+0000] {processor.py:154} INFO - Started process (PID=65208) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:17:16.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:17:16.449+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:17:16.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:17:16.467+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:17:16.464+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:17:16.469+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:17:16.492+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.054 seconds
[2023-04-16T01:17:46.797+0000] {processor.py:154} INFO - Started process (PID=65239) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T01:17:46.804+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T01:17:46.805+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:17:46.805+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T01:17:46.821+0000] {logging_mixin.py:120} INFO - [2023-04-16T01:17:46.819+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T01:17:46.823+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T01:17:46.847+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.065 seconds
[2023-04-16T02:06:17.639+0000] {processor.py:154} INFO - Started process (PID=65262) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T02:06:17.641+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T02:06:17.643+0000] {logging_mixin.py:120} INFO - [2023-04-16T02:06:17.643+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T02:06:17.685+0000] {logging_mixin.py:120} INFO - [2023-04-16T02:06:17.661+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T02:06:17.686+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T02:06:17.727+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.093 seconds
[2023-04-16T02:45:32.902+0000] {processor.py:154} INFO - Started process (PID=65294) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T02:45:32.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T02:45:32.906+0000] {logging_mixin.py:120} INFO - [2023-04-16T02:45:32.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T02:45:32.957+0000] {logging_mixin.py:120} INFO - [2023-04-16T02:45:32.954+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T02:45:32.960+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T02:45:33.062+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.165 seconds
[2023-04-16T03:18:36.336+0000] {processor.py:154} INFO - Started process (PID=65316) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T03:18:36.341+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T03:18:36.359+0000] {logging_mixin.py:120} INFO - [2023-04-16T03:18:36.358+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T03:18:36.429+0000] {logging_mixin.py:120} INFO - [2023-04-16T03:18:36.422+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T03:18:36.435+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T03:18:36.557+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.246 seconds
[2023-04-16T04:01:48.474+0000] {processor.py:154} INFO - Started process (PID=65347) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T04:01:48.482+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T04:01:48.490+0000] {logging_mixin.py:120} INFO - [2023-04-16T04:01:48.490+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T04:01:48.524+0000] {logging_mixin.py:120} INFO - [2023-04-16T04:01:48.521+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T04:01:48.526+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T04:01:48.563+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.093 seconds
[2023-04-16T04:59:07.023+0000] {processor.py:154} INFO - Started process (PID=65378) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T04:59:07.034+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T04:59:07.077+0000] {logging_mixin.py:120} INFO - [2023-04-16T04:59:07.076+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T04:59:07.136+0000] {logging_mixin.py:120} INFO - [2023-04-16T04:59:07.127+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T04:59:07.155+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T04:59:07.344+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.325 seconds
[2023-04-16T06:02:43.715+0000] {processor.py:154} INFO - Started process (PID=65400) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T06:02:43.720+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T06:02:43.724+0000] {logging_mixin.py:120} INFO - [2023-04-16T06:02:43.723+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T06:02:43.768+0000] {logging_mixin.py:120} INFO - [2023-04-16T06:02:43.756+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T06:02:43.779+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T06:02:43.845+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.148 seconds
[2023-04-16T06:54:26.200+0000] {processor.py:154} INFO - Started process (PID=65431) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T06:54:26.203+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T06:54:26.204+0000] {logging_mixin.py:120} INFO - [2023-04-16T06:54:26.204+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T06:54:26.234+0000] {logging_mixin.py:120} INFO - [2023-04-16T06:54:26.226+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T06:54:26.238+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T06:54:26.279+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.086 seconds
[2023-04-16T08:11:17.133+0000] {processor.py:154} INFO - Started process (PID=65454) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T08:11:17.136+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T08:11:17.144+0000] {logging_mixin.py:120} INFO - [2023-04-16T08:11:17.144+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T08:11:17.164+0000] {logging_mixin.py:120} INFO - [2023-04-16T08:11:17.161+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T08:11:17.175+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T08:11:17.210+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.090 seconds
[2023-04-16T08:50:56.170+0000] {processor.py:154} INFO - Started process (PID=65485) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T08:50:56.219+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T08:50:56.236+0000] {logging_mixin.py:120} INFO - [2023-04-16T08:50:56.236+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T08:50:56.391+0000] {logging_mixin.py:120} INFO - [2023-04-16T08:50:56.381+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T08:50:56.408+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T08:50:56.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.606 seconds
[2023-04-16T09:31:23.932+0000] {processor.py:154} INFO - Started process (PID=65516) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T09:31:23.934+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T09:31:23.936+0000] {logging_mixin.py:120} INFO - [2023-04-16T09:31:23.936+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T09:31:23.983+0000] {logging_mixin.py:120} INFO - [2023-04-16T09:31:23.953+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T09:31:23.985+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T09:31:24.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.095 seconds
[2023-04-16T10:55:17.132+0000] {processor.py:154} INFO - Started process (PID=65538) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T10:55:17.140+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T10:55:17.147+0000] {logging_mixin.py:120} INFO - [2023-04-16T10:55:17.146+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T10:55:17.246+0000] {logging_mixin.py:120} INFO - [2023-04-16T10:55:17.223+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T10:55:17.258+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T10:55:17.376+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.265 seconds
[2023-04-16T12:18:09.751+0000] {processor.py:154} INFO - Started process (PID=65570) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T12:18:09.761+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T12:18:09.764+0000] {logging_mixin.py:120} INFO - [2023-04-16T12:18:09.764+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T12:18:09.805+0000] {logging_mixin.py:120} INFO - [2023-04-16T12:18:09.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T12:18:09.807+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T12:18:09.850+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.106 seconds
[2023-04-16T13:41:21.448+0000] {processor.py:154} INFO - Started process (PID=65592) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T13:41:21.450+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T13:41:21.451+0000] {logging_mixin.py:120} INFO - [2023-04-16T13:41:21.451+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T13:41:21.557+0000] {logging_mixin.py:120} INFO - [2023-04-16T13:41:21.542+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T13:41:21.559+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T13:41:21.633+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.192 seconds
[2023-04-16T15:04:32.592+0000] {processor.py:154} INFO - Started process (PID=65623) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T15:04:32.598+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T15:04:32.601+0000] {logging_mixin.py:120} INFO - [2023-04-16T15:04:32.601+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T15:04:32.618+0000] {logging_mixin.py:120} INFO - [2023-04-16T15:04:32.615+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T15:04:32.621+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T15:04:32.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.074 seconds
[2023-04-16T16:14:38.641+0000] {processor.py:154} INFO - Started process (PID=65645) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T16:14:38.649+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T16:14:38.659+0000] {logging_mixin.py:120} INFO - [2023-04-16T16:14:38.659+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T16:14:38.792+0000] {logging_mixin.py:120} INFO - [2023-04-16T16:14:38.762+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T16:14:38.800+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T16:14:38.968+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.354 seconds
[2023-04-16T17:19:20.456+0000] {processor.py:154} INFO - Started process (PID=65675) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T17:19:20.459+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T17:19:20.463+0000] {logging_mixin.py:120} INFO - [2023-04-16T17:19:20.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T17:19:20.522+0000] {logging_mixin.py:120} INFO - [2023-04-16T17:19:20.511+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T17:19:20.531+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T17:19:20.684+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.249 seconds
[2023-04-16T18:00:00.413+0000] {processor.py:154} INFO - Started process (PID=65697) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T18:00:00.418+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T18:00:00.463+0000] {logging_mixin.py:120} INFO - [2023-04-16T18:00:00.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T18:00:01.000+0000] {logging_mixin.py:120} INFO - [2023-04-16T18:00:00.994+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T18:00:01.016+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T18:00:01.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.717 seconds
[2023-04-16T19:14:10.921+0000] {processor.py:154} INFO - Started process (PID=65727) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T19:14:10.929+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T19:14:11.001+0000] {logging_mixin.py:120} INFO - [2023-04-16T19:14:11.001+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T19:14:11.069+0000] {logging_mixin.py:120} INFO - [2023-04-16T19:14:11.057+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T19:14:11.075+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T19:14:11.126+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.220 seconds
[2023-04-16T19:38:57.269+0000] {processor.py:154} INFO - Started process (PID=65758) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T19:38:57.277+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T19:38:57.279+0000] {logging_mixin.py:120} INFO - [2023-04-16T19:38:57.278+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T19:38:57.301+0000] {logging_mixin.py:120} INFO - [2023-04-16T19:38:57.298+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T19:38:57.302+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T19:38:57.331+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.067 seconds
[2023-04-16T20:12:32.800+0000] {processor.py:154} INFO - Started process (PID=65790) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T20:12:32.810+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T20:12:32.815+0000] {logging_mixin.py:120} INFO - [2023-04-16T20:12:32.814+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T20:12:32.869+0000] {logging_mixin.py:120} INFO - [2023-04-16T20:12:32.862+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T20:12:32.871+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T20:12:32.978+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.196 seconds
[2023-04-16T21:15:35.954+0000] {processor.py:154} INFO - Started process (PID=65811) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T21:15:35.957+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T21:15:35.958+0000] {logging_mixin.py:120} INFO - [2023-04-16T21:15:35.958+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T21:15:35.982+0000] {logging_mixin.py:120} INFO - [2023-04-16T21:15:35.977+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T21:15:35.983+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T21:15:36.009+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.060 seconds
[2023-04-16T22:35:56.804+0000] {processor.py:154} INFO - Started process (PID=65843) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T22:35:56.806+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T22:35:56.807+0000] {logging_mixin.py:120} INFO - [2023-04-16T22:35:56.807+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T22:35:56.850+0000] {logging_mixin.py:120} INFO - [2023-04-16T22:35:56.839+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T22:35:56.852+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T22:35:56.888+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.090 seconds
[2023-04-16T23:33:27.718+0000] {processor.py:154} INFO - Started process (PID=65874) to work on /opt/airflow/dags/snow_air.py
[2023-04-16T23:33:27.727+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/snow_air.py for tasks to queue
[2023-04-16T23:33:27.774+0000] {logging_mixin.py:120} INFO - [2023-04-16T23:33:27.772+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/snow_air.py
[2023-04-16T23:33:27.824+0000] {logging_mixin.py:120} INFO - [2023-04-16T23:33:27.818+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/snow_air.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/snow_air.py", line 3, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-04-16T23:33:27.834+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/snow_air.py
[2023-04-16T23:33:27.912+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/snow_air.py took 0.246 seconds
